[package]
name = "bmp180"
version = "0.1.0"
authors = ["Mike Walters <mike@flomp.net>"]

[dependencies]
byteorder = { version = "*", default-features = false }
embedded-hal = "*"

[dev_dependencies]
embedded-hal-mock = "*"
linux-embedded-hal = "*"
